---
train:
  params:
    batch_size: 256
    epoch: 12
    lr: 0.001
    decay: 0.1
    decay_step:
      - 8
  save:
    save_path: "saves"
    model_name: "AFF-Net"
    step: 1
  data:
    path: "/home/islabshi/workspace-cloud/koki.murata/datasets/processed/MPII_2d"
test:
   load:
      begin_step: 1
      end_step: 12
      steps: 1
      model_name: "AFF-Net"
      load_path: "saves"
   data:
      path: "/home/islabshi/workspace-cloud/koki.murata/datasets/processed/MPII_2d"
